const commonSeoFields = [
  { name: "seoTitle", label: "SEO title", type: "text" },
  { name: "seoDescription", label: "Meta description", type: "textarea" },
  { name: "canonicalUrl", label: "Canonical URL", type: "url" },
  { name: "ogTitle", label: "Open Graph title", type: "text" },
  { name: "ogDescription", label: "Open Graph description", type: "textarea" },
  { name: "ogImage", label: "Open Graph image", type: "image" },
  { name: "noindex", label: "No index", type: "checkbox" },
  { name: "nofollow", label: "No follow", type: "checkbox" },
];

export const resourceConfigs = {
  pages: {
    label: "Pages",
    singular: "Page",
    collection: "pages",
    titleField: "title",
    previewBase: "",
    fields: [
      { name: "title", label: "Page name", type: "text", required: true },
      { name: "heading", label: "Page heading", type: "text" },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "route", label: "Public route", type: "text", placeholder: "/about" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "coverImage", label: "Cover image", type: "image" },
      { name: "blocks", label: "Page blocks", type: "blocks" },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "PUBLISHED"], defaultValue: "DRAFT" },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
      ...commonSeoFields,
    ],
  },
  services: {
    label: "Services",
    singular: "Service",
    collection: "services",
    titleField: "title",
    previewBase: "/services",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "icon", label: "Icon name", type: "text", placeholder: "wordpress, elementor, cart..." },
      { name: "shortDescription", label: "Short description", type: "textarea" },
      { name: "fullDescription", label: "Full description", type: "textarea" },
      { name: "features", label: "Features", type: "list" },
      { name: "ctaText", label: "CTA text", type: "text" },
      { name: "ctaUrl", label: "CTA URL", type: "url" },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "PUBLISHED"], defaultValue: "DRAFT" },
      ...commonSeoFields,
    ],
  },
  projects: {
    label: "Works",
    singular: "Project",
    collection: "projects",
    titleField: "title",
    previewBase: "/works",
    fields: [
      { name: "title", label: "Project title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "excerpt", label: "Short summary", type: "textarea" },
      { name: "featuredImage", label: "Featured image", type: "image" },
      { name: "gallery", label: "Gallery images", type: "image-list" },
      { name: "clientName", label: "Client name", type: "text" },
      { name: "category", label: "Category slug", type: "text" },
      { name: "completionDate", label: "Completion date", type: "date" },
      { name: "projectUrl", label: "Project URL", type: "url" },
      { name: "services", label: "Services provided", type: "list" },
      { name: "technologies", label: "Technologies", type: "list" },
      { name: "challenge", label: "Challenge", type: "textarea" },
      { name: "solution", label: "Solution", type: "textarea" },
      { name: "results", label: "Results", type: "textarea" },
      { name: "testimonial", label: "Project testimonial", type: "textarea" },
      { name: "featured", label: "Featured project", type: "checkbox" },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "PUBLISHED"], defaultValue: "DRAFT" },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
      ...commonSeoFields,
    ],
  },
  testimonials: {
    label: "Reviews",
    singular: "Review",
    collection: "testimonials",
    titleField: "clientName",
    fields: [
      { name: "reviewText", label: "Review", type: "textarea", required: true },
      { name: "clientName", label: "Client name", type: "text", required: true },
      { name: "clientPosition", label: "Position", type: "text" },
      { name: "clientCompany", label: "Company", type: "text" },
      { name: "clientImage", label: "Client image", type: "image" },
      { name: "rating", label: "Rating", type: "number" },
      { name: "featured", label: "Featured review", type: "checkbox" },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "PUBLISHED"], defaultValue: "DRAFT" },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
    ],
  },
  posts: {
    label: "Blog",
    singular: "Article",
    collection: "posts",
    titleField: "title",
    previewBase: "/blog",
    fields: [
      { name: "title", label: "Article title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "coverImage", label: "Cover image", type: "image" },
      { name: "content", label: "Article blocks", type: "blocks" },
      { name: "category", label: "Category slug", type: "text" },
      { name: "tags", label: "Tag slugs", type: "list" },
      { name: "readingTime", label: "Reading time (minutes)", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "PUBLISHED"], defaultValue: "DRAFT" },
      { name: "featured", label: "Featured article", type: "checkbox" },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
      ...commonSeoFields,
    ],
  },
  categories: {
    label: "Categories",
    singular: "Category",
    collection: "categories",
    titleField: "name",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "scope", label: "Used for", type: "select", options: ["project", "post"], defaultValue: "post" },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "PUBLISHED"], defaultValue: "PUBLISHED" },
    ],
  },
  tags: {
    label: "Tags",
    singular: "Tag",
    collection: "tags",
    titleField: "name",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
    ],
  },
  navigation: {
    label: "Navigation",
    singular: "Menu item",
    collection: "navigation",
    titleField: "label",
    fields: [
      { name: "label", label: "Label", type: "text", required: true },
      { name: "url", label: "URL", type: "url", required: true },
      { name: "order", label: "Display order", type: "number", defaultValue: 0 },
      { name: "visible", label: "Visible", type: "checkbox", defaultValue: true },
    ],
  },
};

export const dashboardRouteMap = {
  pages: "pages",
  services: "services",
  works: "projects",
  reviews: "testimonials",
  blog: "posts",
  categories: "categories",
  tags: "tags",
  navigation: "navigation",
};

export function getResourceConfig(resource) {
  return resourceConfigs[resource] || null;
}
